apiVersion: v1
kind: Pod
metadata:
  name: "mydb"
  labels:
    app: mydb
spec:
  containers:
  - name: "mydb"
    image: "mysql:5.7"
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: redhat
    - name: MYSQL_USER
      value: kani
    - name: MYSQL_PASS
      value: redhat
    - name: MYSQL_DATABASE
      value: wpdb    