apiVersion: v1
kind: ReplicationController
metadata:
  name: "myrc1"
  labels:
    app: "web"
spec:
  replicas: 4
  selector:                                       #find this 
    app: "web"
  template:                                      #else launch this
    metadata:
      name: "mypod1"
      labels:
        app: "web"
    spec:
      containers:
        - name: "myrc1"
          image: "vimal13/apache-webserver-php"